import type { APIRoute } from "astro";
import { ROUTES, SITE_CONFIG } from "@/site-config";
import { CANDIDATE_FAQS, EMPLOYER_FAQS } from "@/data/faqs";
import { OPEN_SCOPE_LINE, ROLE_FAMILIES } from "@/data/roles";
import { LIFECYCLE, PROCESS_PHASES } from "@/data/process";
import { VERIFIED_PROOF } from "@/data/proof";

export const GET: APIRoute = () => {
  const url = (path: string) => `${SITE_CONFIG.url}${path}`;

  const lines = [
    `# ${SITE_CONFIG.brand} — Full Knowledge Base`,
    "",
    `> ${SITE_CONFIG.description}`,
    "",
    "## Summary of Service",
    "",
    "Cube27 Talent provides managed hiring and team building for specialists, complete teams, and senior leadership across global organizations. Candidates are assessed through role-specific tasks and practitioner interviews, providing employers with evidence-backed shortlists for confident hiring decisions.",
    "",
    "## Core Principles & Delivery Model",
    "",
    "- **Role-specific assessments**: Candidates complete real-world exercises relevant to the position.",
    "- **Practitioner interviews**: Experienced domain practitioners review candidate work and conduct evaluations.",
    "- **Human judgment**: AI assists sourcing and screening; human experts make every assessment and hiring decision.",
    "- **One partner across the lifecycle**: Managed support spanning hiring, onboarding, payroll/administration, and ongoing team evolution.",
    "- **Standards that scale**: Coordination across contracts, applicable local labor and IP requirements, payroll, culture onboarding, and client-defined performance reviews.",
    "",
    "## Areas of Expertise & Role Families",
    "",
    ...ROLE_FAMILIES.flatMap((family) => [
      `### ${family.name}`,
      "",
      family.blurb,
      "",
      "**Typical roles:**",
      ...family.roles.map((role) => `- ${role}`),
      "",
    ]),
    `*${OPEN_SCOPE_LINE}*`,
    "",
    "## Why Organizations Work With Us",
    "",
    "Our core team has led and built teams serving Fortune 500 companies, held CTO and other C-suite roles, and built functions from the ground up.",
    "",
    "## Workforce Compliance & Culture",
    "",
    "We coordinate the standards behind every hire—from contracts and payroll to applicable local labor and IP requirements, culture onboarding, and client-defined performance reviews.",
    "",
    "- Contracts and applicable local labor/IP requirements",
    "- Payroll and workforce administration",
    "- Culture onboarding led by HR specialists working with the client",
    "- HR-facilitated reviews against client-defined criteria",
    "",
    "## The 4-Phase Hiring Process",
    "",
    ...PROCESS_PHASES.flatMap((phase) => [
      `### ${phase.name}`,
      "",
      phase.summary,
      "",
      ...phase.points.map((pt) => `- ${pt}`),
      "",
    ]),
    "## Ongoing Lifecycle Support",
    "",
    ...LIFECYCLE.flatMap((stage) => [`### ${stage.title}`, "", stage.body, ""]),
    "## Approved Proof Metrics",
    "",
    ...VERIFIED_PROOF.map((p) => `- **${p.value}**: ${p.label}`),
    "",
    "## Explicit Boundaries & Non-Claims",
    "",
    "- No assured placement, hiring speed, shortlist timing, overseas travel, relocation, or visa approval.",
    "- No published pricing or commercial structure on public channels.",
    "- No live candidate inventory, self-serve marketplace, or automated software platform.",
    "- Compliance coordination does not imply legal advice, certification ownership, or universal legal liability.",
    "",
    "## Site Directory & Routes",
    "",
    `- [Home](${url(ROUTES.home)}): Managed hiring overview, proof metrics, cross-functional scope, compliance, and ongoing support.`,
    `- [How we hire](${url(ROUTES.how)}): Evidence-based assessment methodology, practitioner interviews, and selection process.`,
    `- [Why us](${url(ROUTES.whyUs)}): Operator experience, hiring standards, workforce compliance, and approved proof.`,
    `- [Build your team](${url(ROUTES.hire)}): Employer enquiry form and hiring consultation request.`,
    `- [For talent](${url(ROUTES.join)}): Candidate network application and career opportunities.`,
    `- [Overview index](${url("/llms.txt")}): Machine-readable concise summary.`,
    "",
    "## Frequently Asked Questions from Employers",
    "",
    ...EMPLOYER_FAQS.flatMap((faq) => [`### ${faq.q}`, "", faq.a, ""]),
    "## Frequently Asked Questions from Candidates",
    "",
    ...CANDIDATE_FAQS.flatMap((faq) => [`### ${faq.q}`, "", faq.a, ""]),
    "## Organization & Contact Information",
    "",
    `- Legal Entity: ${SITE_CONFIG.organization.legalName}`,
    `- General & Candidate Inquiries: ${SITE_CONFIG.organization.email}`,
    `- Data Protection & Privacy Contact: ${SITE_CONFIG.organization.privacyEmail}`,
    `- Address: ${SITE_CONFIG.organization.address.streetAddress}, ${SITE_CONFIG.organization.address.addressLocality}, ${SITE_CONFIG.organization.address.addressRegion} ${SITE_CONFIG.organization.address.postalCode}, ${SITE_CONFIG.organization.address.addressCountry}`,
    `- Parent Company: ${SITE_CONFIG.organization.parentSite}`,
    `- Official LinkedIn: ${SITE_CONFIG.organization.sameAs[0]}`,
    "",
  ];

  return new Response(lines.join("\n"), {
    headers: { "content-type": "text/plain; charset=utf-8" },
  });
};
