import type { APIRoute } from "astro";
import { ROUTES, SITE_CONFIG } from "@/site-config";
import { CANDIDATE_FAQS, EMPLOYER_FAQS } from "@/data/faqs";
import {
  OPEN_SCOPE_LINE,
  ROLE_FAMILIES,
  SECURITY_DISCLAIMER,
  SECURITY_FRAMEWORKS,
} from "@/data/roles";
import { LIFECYCLE, PROCESS_PHASES } from "@/data/process";
import { VERIFIED_PROOF } from "@/data/proof";

export const GET: APIRoute = () => {
  const url = (path: string) => `${SITE_CONFIG.url}${path}`;

  const lines = [
    `# ${SITE_CONFIG.brand} — Full Knowledge Base`,
    "",
    `> ${SITE_CONFIG.description}`,
    "",
    "## Summary of Service",
    "",
    "Cube27 Talent provides managed hiring and team building for specialists, complete teams, security functions, and senior leadership across global organizations. Candidates are assessed through role-specific tasks and practitioner interviews, providing employers with evidence-backed shortlists for confident hiring decisions.",
    "",
    "## Core Principles & Delivery Model",
    "",
    "- **Role-specific assessments**: Candidates complete real-world exercises relevant to the position.",
    "- **Practitioner interviews**: Experienced domain practitioners review candidate work and conduct evaluations.",
    "- **Human judgment**: AI assists sourcing and screening; human experts make every assessment and hiring decision.",
    "- **One partner across the lifecycle**: Managed support spanning hiring, onboarding, payroll/administration, and ongoing team evolution.",
    "",
    "## Areas of Expertise & Role Families",
    "",
    ...ROLE_FAMILIES.flatMap((family) => [
      `### ${family.name}`,
      "",
      family.blurb,
      "",
      "**Typical roles:**",
      ...family.roles.map((role) => `- ${role}`),
      "",
    ]),
    `*${OPEN_SCOPE_LINE}*`,
    "",
    "## Security & Compliance Team Building",
    "",
    "We build dedicated security, engineering, GRC, and audit teams to help organizations work toward major international standards:",
    "",
    ...SECURITY_FRAMEWORKS.map((standard) => `- ${standard}`),
    "",
    `*${SECURITY_DISCLAIMER}*`,
    "",
    "## The 4-Phase Hiring Process",
    "",
    ...PROCESS_PHASES.flatMap((phase) => [
      `### ${phase.name}`,
      "",
      phase.summary,
      "",
      ...phase.points.map((pt) => `- ${pt}`),
      "",
    ]),
    "## Ongoing Lifecycle Support",
    "",
    ...LIFECYCLE.flatMap((stage) => [
      `### ${stage.title}`,
      "",
      stage.body,
      "",
    ]),
    "## Approved Proof Metrics",
    "",
    ...VERIFIED_PROOF.map((p) => `- **${p.value}**: ${p.label}`),
    "",
    "## Explicit Boundaries & Non-Claims",
    "",
    "- No assured placement, hiring speed, shortlist timing, overseas travel, relocation, or visa approval.",
    "- No published pricing or commercial structure on public channels.",
    "- No live candidate inventory, self-serve marketplace, or automated software platform.",
    "- Cube27 does not issue security certifications directly; we recruit and build teams that implement the required controls.",
    "",
    "## Site Directory & Routes",
    "",
    `- [Home](${url(ROUTES.home)}): Managed hiring overview, proof metrics, expertise, and ongoing support.`,
    `- [How we hire](${url(ROUTES.how)}): Evidence-based assessment methodology, practitioner interviews, and selection process.`,
    `- [Expertise](${url(ROUTES.expertise)}): Cross-functional hiring, security compliance teams, and leadership search.`,
    `- [Build your team](${url(ROUTES.hire)}): Employer requirement form and hiring consultation request.`,
    `- [For talent](${url(ROUTES.join)}): Candidate network application and career opportunities.`,
    `- [Overview index](${url("/llms.txt")}): Machine-readable concise summary.`,
    "",
    "## Frequently Asked Questions from Employers",
    "",
    ...EMPLOYER_FAQS.flatMap((faq) => [`### ${faq.q}`, "", faq.a, ""]),
    "## Frequently Asked Questions from Candidates",
    "",
    ...CANDIDATE_FAQS.flatMap((faq) => [`### ${faq.q}`, "", faq.a, ""]),
    "## Organization & Contact Information",
    "",
    `- Legal Entity: ${SITE_CONFIG.organization.legalName}`,
    `- General & Candidate Inquiries: ${SITE_CONFIG.organization.email}`,
    `- Data Protection & Privacy Contact: ${SITE_CONFIG.organization.privacyEmail}`,
    `- Address: ${SITE_CONFIG.organization.address.streetAddress}, ${SITE_CONFIG.organization.address.addressLocality}, ${SITE_CONFIG.organization.address.addressRegion} ${SITE_CONFIG.organization.address.postalCode}, ${SITE_CONFIG.organization.address.addressCountry}`,
    `- Parent Company: ${SITE_CONFIG.organization.parentSite}`,
    `- Official LinkedIn: ${SITE_CONFIG.organization.sameAs[0]}`,
    "",
  ];

  return new Response(lines.join("\n"), {
    headers: { "content-type": "text/plain; charset=utf-8" },
  });
};
